### ISSUE TITLE
ui failed build

### ISSUE THREAD

**Issue by tygrysio** [NVIDIA-AI-IOT/deepstream_360_d_smart_parking_application#6]
After run start.sh
Building ui
Step 1/17 : FROM node:8 as ui-builder
ERROR: Service 'ui' failed to build: Error parsing reference: "node:8 as ui-builder" is not a valid repository/tag: invalid reference format

**Comment by tygrysio** [comment]
The problem is multi-stage builds in Dockerfile in nxnix-ui. My docker version (1.13.1) not support this.

**Comment by aiyerganapathy** [comment]
Hi,

This application was tested on the latest version of docker in Ubuntu 16.04. Can you please try the same. Let us know if you still have problems by opening a new issue.
