### ISSUE TITLE
VMS for managing hundreds of cameras 

### ISSUE THREAD

**Issue by jhagege** [NVIDIA-AI-IOT/deepstream_360_d_smart_parking_application#7]
Thanks for this great repository.
Do I need a VMS to manage hundreds cameras as you are describing in a DeepStream application  ? 
In the setup you are describing, how are the cameras synchronised precisely and have their timestamps in-sync, video is encoded in the correct format, configured etc.  
I thought only VMS could provide that functionality.
Thanks for your clarifications :)

**Comment by velushomaz** [comment]
@jhagege not the devs but I assume the times are synchronised with NTPs and the videos are exported with 2fps. 

I know one can request camera APIs (Axis come to mind) to serve you fixed width/res/fps as source and the deepstream app should be able to take them as source.

**Comment by jhagege** [comment]
Thanks !
